### PR TITLE
Add missing JS

### PR DESCRIPTION
**Pull request by marcos-arranz**
Add missing JS build after `yarn build` in order to fix https://github.com/pleo-io/assign-random-codeowners/actions/runs/4162147471/jobs/7200959483

### CODE REVIEW

**Comment by andersfischernielsen** [comment]
#40 should take care of this, so we can save a push to `main` here

**Comment by marcos-arranz** [comment]
> https://github.com/pleo-io/assign-random-codeowners/pull/40 should take care of this, so we can save a push to main here
If we still keep `dist` in `git` then we have to merge this as currently the status between `ts` and `js` is inconsistent. My vote, is to remove `dist` from `git` though.

**Comment by andersfischernielsen** [comment]
> > #40 should take care of this, so we can save a push to main here
> 
> If we still keep `dist` in `git` then we have to merge this as currently the status between `ts` and `js` is inconsistent. My vote, is to remove `dist` from `git` though.

@marcos-arranz But `dist` as well as `node_modules` need to be present in the repository. This is a requirement of GitHub Actions. So I don’t understand why you’d remove it? 🤔

The build output is the same if you `yarn build` locally or on CI, so I also don’t understand your point on inconsistency. 

Once #40 is released the release job will build `dist` and it’ll be pushed to the repository. Whether you’ve rebuilt it locally or not is then irrelevant 😄

But please LMK, wondering if I’m missing something here

**Comment by marcos-arranz** [comment]
> > > #40 should take care of this, so we can save a push to main here
> > 
> > 
> > If we still keep `dist` in `git` then we have to merge this as currently the status between `ts` and `js` is inconsistent. My vote, is to remove `dist` from `git` though.
> 
> @marcos-arranz But `dist` as well as `node_modules` need to be present in the repository. This is a requirement of GitHub Actions. So I don’t understand why you’d remove it? 🤔
> 
> The build output is the same if you `yarn build` locally or on CI, so I also don’t understand your point on inconsistency.
> 
> Once #40 is released the release job will build `dist` and it’ll be pushed to the repository. Whether you’ve rebuilt it locally or not is then irrelevant 😄
> 
> But please LMK, wondering if I’m missing something here

Ah, I see. Makes sense.

**Pull request closed without merging**
